set( CMAKE_SYSTEM_NAME Linux )
set( SDKTARGETSYSROOT /data/o3d3xx/poky/1.8.1/sysroots/armv7ahf-vfp-neon-poky-linux-gnueabi )
set( OECORE_NATIVE_SYSROOT /data/o3d3xx/poky/1.8.1/sysroots/i686-pokysdk-linux )
set( OE_CFLAGS " -O2 -pipe -g -feliminate-unused-debug-types" )
set( OE_LD_FLAGS " -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed" )
set( OE_ARCH_CFLAGS " -march=armv7-a -mfloat-abi=hard -mfpu=neon" )
set( CMAKE_C_COMPILER  ${OECORE_NATIVE_SYSROOT}/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc )
set( CMAKE_CXX_COMPILER  ${OECORE_NATIVE_SYSROOT}/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++ )
set( CMAKE_CXX_FLAGS "${OE_ARCH_CFLAGS} --sysroot=${SDKTARGETSYSROOT} ${OE_CFLAGS}"  CACHE STRING "" FORCE )
set( CMAKE_C_FLAGS "${OE_ARCH_CFLAGS} --sysroot=${SDKTARGETSYSROOT} ${OE_CFLAGS}" CACHE STRING "" FORCE ) 
set( CMAKE_LDFLAGS_FLAGS "${OE_LD_FLAGS}" CACHE STRING "" FORCE ) 
set( CMAKE_LIBRARY_PATH ${OECORE_NATIVE_SYSROOT} ${SDKTARGETSYSROOT})
set( CMAKE_FIND_ROOT_PATH ${OECORE_NATIVE_SYSROOT}  )
set( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER )
set( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )

